# Generated by Django 4.1.4 on 2023-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Buutti', max_length=50),
            preserve_default=False,
        ),
    ]
